CREATE TABLE gamereview_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_title TEXT NOT NULL,
    content TEXT NOT NULL,
    rating INTEGER NOT NULL,
    game_id INTEGER REFERENCES gamereview_games(id) ON DELETE SET NULL,
    modified TIMESTAMP NOT NULL DEFAULT now(),
    user_id INTEGER REFERENCES gamereview_users(id)

);